language: generic
os: osx
osx_image: xcode10.1

matrix:
  include:
    - os: linux

matrix:
  fast_finish: true

notifications:
  email: false

before_script:
  - brew services restart postgresql

script:
  - bash -n *.sh
  - ./script/setup
  - export PS1
  - bash -c "source ~/.bashrc"
  - zsh -c "source ~/.zshrc"
