tap "aljohri/personal"
tap "aws/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "wpmedia/perso-tools" unless ENV['CI']

# installs java8, must be first
cask "adoptopenjdk8"

brew "antigen"
brew "archey"
brew "arp-scan"
brew "gettext"
brew "libffi"
brew "readline"
brew "python"
brew "glib"
brew "autoconf"
brew "automake"
brew "awscli"
brew "openssl"
brew "awslogs"
brew "bash"
brew "bat"
brew "binutils"
brew "bison"
brew "boot-clj"
brew "brightness"
brew "dvc"
brew "freetype"
brew "cheat"
brew "clojure"
brew "colordiff"
brew "coreutils"
brew "cowsay"
brew "crunch"
brew "csvkit"
brew "dex2jar"
brew "ghostscript"
brew "djvu2pdf"
brew "dos2unix"
brew "duti"
brew "ec2-api-tools"
brew "elasticsearch", restart_service: true
brew "exa"
brew "expect"
brew "gnutls"
brew "ffmpeg"
brew "fish"
brew "flex"
brew "flyway"
brew "fortune"
brew "fzf"
brew "libxml2"
brew "libtool"
brew "qt"
brew "python@2"
brew "gist"
brew "git"
brew "gnu-sed"
brew "gnu-time"
brew "libgpg-error"
brew "libusb"
brew "gnupg"
brew "go"
brew "graphviz"
brew "grep"
brew "gtk+"
brew "html2text"
brew "htop"
brew "httpie"
brew "hub"
brew "hydra", link: false
brew "imagemagick"
brew "intltool"
brew "jq"
brew "jsonpp"
brew "kafka"
brew "leiningen"
brew "libarchive"
brew "libgit2"
brew "libglade"
brew "libiconv"
brew "libxslt"
brew "lighttpd"
brew "lzlib"
brew "mas"
brew "maven"
brew "memtester"
brew "mercurial"
brew "moreutils"
brew "most"
brew "mysql", restart_service: true
brew "ncdu"
brew "ncrack"
brew "nmap"
brew "node"
brew "oath-toolkit"
brew "openconnect"
brew "p7zip"
brew "parquet-tools"
brew "pidof"
brew "pipenv"
brew "pipx"
brew "postgresql", restart_service: true
brew "postgis"
brew "pre-commit"
brew "pssh"
brew "pyenv"
brew "python-yq"
brew "qpdf"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "renameutils"
brew "ripgrep"
brew "ripgrep-all"
brew "ruby"
brew "sdl"
brew "shellcheck"
brew "speedtest-cli"
brew "ssh-copy-id"
brew "sshfs"
brew "sshpass"
brew "subversion", link: false
brew "tcl-tk"
brew "tcpflow"
brew "telnet"
brew "texinfo"
brew "tig"
brew "tldr"
brew "tor", restart_service: true
brew "tree"
brew "watch"
brew "wget"
brew "ydiff"
brew "youtube-dl"
brew "zsh"
brew "aljohri/personal/openconnect-okta-helper"
brew "aws/tap/aws-sam-cli"
brew "heroku/brew/heroku"
brew "wpmedia/perso-tools/clokta-utils" unless ENV['CI']
brew "wpmedia/perso-tools/ec2" unless ENV['CI']
brew "wpmedia/perso-tools/emr" unless ENV['CI']
brew "wpmedia/perso-tools/kms" unless ENV['CI']
brew "wpmedia/perso-tools/nile" unless ENV['CI']
brew "wpmedia/perso-tools/perso-apache-spark" unless ENV['CI']
brew "wpmedia/perso-tools/ssm" unless ENV['CI']
cask "1password-cli"
cask "airserver"
cask "android-file-transfer"
cask "android-platform-tools"
cask "balenaetcher"
cask "boostnote"
cask "carbon-copy-cloner"
cask "charles"
cask "cyberduck"
cask "discord"
cask "djay-pro"
cask "djview"
cask "docker"
cask "dropbox"
cask "flash-npapi"
cask "flash-player"
cask "flash-ppapi"
cask "fsnotes"
cask "google-chrome-canary"
cask "google-hangouts"
cask "handbrake"
cask "hyper"
cask "insomnia"
cask "intellij-idea"
cask "iterm2"
cask "java8"
cask "jd-gui"
cask "keepingyouawake"
cask "keybase"
cask "lingon-x"
cask "little-snitch"
cask "logitech-options"
cask "macdown"
cask "mactex"
cask "micro-snitch"
cask "mpv"
cask "notion"
cask "paragon-ntfs"
cask "pdf-expert"
cask "private-internet-access"
cask "provisionql"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "r"
cask "r-app"
cask "robo-3t"
cask "rstudio"
cask "screens-connect"
cask "skitch"
cask "skype"
cask "slack" unless File.directory?("/Applications/Slack.app")
cask "spectacle"
cask "spotify"
cask "steam"
cask "studio-3t"
cask "sublime-text"
cask "tabula"
cask "tad"
cask "teamviewer"
cask "textual"
cask "transmission"
cask "transmit"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc" unless File.directory?("/Applications/VLC.app")
cask "webpquicklook"
cask "webtorrent"
cask "wireshark"
cask "yt-music"
mas "1Password 7", id: 1333542190
mas "DaisyDisk", id: 411643860
mas "Gapplin", id: 768053424
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Leaf", id: 576338668
mas "Notability", id: 736189492
mas "Pocket", id: 568494494
mas "PomoDone App", id: 1096128050
mas "Table Tool", id: 1122008420
mas "Todoist", id: 585829637
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
