cask_args appdir: '/Applications'

tap 'homebrew/core'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'caskroom/fonts'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'homebrew/dupes'
tap 'homebrew/science'
tap 'homebrew/binary'

brew 'mas'
brew 'node'
brew 'nodenv'
brew 'openssl'
brew 'openssl'
brew 'pyenv'
brew 'python'
brew 'python3'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'ripgrep'
brew 'ruby-build'
brew 'tree'

cask 'atom'
cask 'iterm2'
cask 'sublime-text'