winget install -e --id voidtools.Everything
winget install -e --id PrimateLabs.Geekbench
winget install -e --id Google.ChromeBeta
winget install -e --id Microsoft.Skype
winget install -e --id Zoom.Zoom
winget install -e --id StandardNotes.StandardNotes
winget install -e --id Valve.Steam
winget install -e --id SublimeHQ.SublimeText
winget install -e --id TeamViewer.TeamViewer
winget install -e --id VideoLAN.VLC
winget install -e --id Microsoft.VisualStudioCode
winget install -e --id WhatsApp.WhatsApp
winget install -e --id Microsoft.WindowsTerminal
winget install -e --id Iterate.Cyberduck
winget install -e --id Keybase.Keybase
winget install -e --id Spotify.Spotify
winget install -e --id AgileBits.1Password
winget install -e --id Docker.DockerDesktop
winget install -e --id Discord.Discord
winget install -e --id GiorgioTani.PeaZip
winget install -e --id Notion.Notion
winget install -e --id Canonical.Ubuntu
winget install -e --id OpenJS.NodeJS
winget install -e --id Python.Python
winget install -e --id RiotGames.Valorant
winget install -e --id TechPowerUp.GPU-Z
winget install -e --id CPUID.CPU-Z
winget install -e --id CPUID.HWMonitor
winget install -e --id JRSoftware.InnoSetup
winget install -e --id PrivateInternetAccess.PrivateInternetAccess
winget install -e --id Signal.Signal
winget install -e --id SlackTechnologies.Slack
winget install -e --id TickTick.TickTick
winget install -e --id PDFLabs.PDFtkServer
