winget install -e --id voidtools.Everything
winget install -e --id PrimateLabs.Geekbench
winget install -e --id Google.ChromeBeta
winget install -e --id Microsoft.Skype
winget install -e --id Zoom.Zoom
winget install -e --id StandardNotes.StandardNotes
winget install -e --id Valve.Steam
winget install -e --id SublimeHQ.SublimeText
winget install -e --id TeamViewer.TeamViewer
winget install -e --id VideoLAN.VLC
winget install -e --id Microsoft.VisualStudioCode
winget install -e --id WhatsApp.WhatsApp
winget install -e --id Microsoft.WindowsTerminal
winget install -e --id Iterate.Cyberduck
winget install -e --id Keybase.Keybase
winget install -e --id Spotify.Spotify
winget install -e --id AgileBits.1Password
winget install -e --id Docker.DockerDesktop
