# Extra env variables
# env = MY_GLOBAL_ENV,setting

# Add ~/bin to PATH
env = PATH,$HOME/bin:$PATH

# HiDPI scaling for XWayland apps (since force_zero_scaling = true)
env = GDK_SCALE,2
env = STEAM_FORCE_DESKTOPUI_SCALING,2
