#!/bin/sh
# Install all dotfiles into the home directory
# Adapted from https://github.com/MikeMcQuaid/dotfiles/blob/master/script/setup

set -e

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

[ $(uname -s) = "Darwin" ] && export OSX=1 && export UNIX=1
[ $(uname -s) = "Linux" ] && export LINUX=1 && export UNIX=1
uname -s | grep -q "_NT-" && export WINDOWS=1

echo "UNIX: $UNIX"
echo "OSX: $OSX"
echo "LINUX: $LINUX"
echo "WINDOWS: $WINDOWS"

for DOTFILE in *; do
  HOMEFILE="$HOME/.$DOTFILE"
  [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"
  DIRFILE="$DOTFILESDIR/$DOTFILE"
  
  # skip script folder and text/markdown files
  echo $DOTFILE | egrep -q '(^script/$|\.txt$|\.md$)' && continue

  # remove .sh extension
  echo $DOTFILE | grep -q '\.sh' \
    && HOMEFILE="$HOME/.$(echo $DOTFILE | sed -e 's/\.sh//')"

  if [ $UNIX ]
  then
    if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]
    then
      ln -sfv "$DIRFILE" "$HOMEFILE"
    else
      rm -rfv "$HOMEFILE"
      ln -sv "$DIRFILE" "$HOMEFILE"
    fi
  else
    cp -rv "$DIRFILE" "$HOMEFILE"
  fi
done

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

append_to_file() {
  local file="$1"
  local text="$2"

  if [ -e "$file" ];
  then
    if ! grep -qs "^$text$" "$file"; then
      printf "\n%s\n" "$text" >> "$file"
    fi
  else
    touch "$file"
    printf "%s\n" "$text" >> "$file"
  fi
}

if [ $OSX ]
then
  brew bundle --global || true

  mkdir -p "$HOME/Library/Application Support/Sublime Text 3/Installed Packages/"
  if [ ! -f "$HOME/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package" ]; then
    # http://stackoverflow.com/questions/19529999/add-package-control-in-sublime-text-3-through-the-command-line
    echo "Installing Sublime Text 3 Package Manager"
    wget http://sublime.wbond.net/Package%20Control.sublime-package -P "$HOME/Library/Application Support/Sublime Text 3/Installed Packages/"
  fi

  duti -s com.sublimetext.3 java all
  duti -s com.sublimetext.3 js all
  duti -s com.sublimetext.3 py all
  duti -s com.sublimetext.3 rb all
  duti -s com.sublimetext.3 sh all
  duti -s com.sublimetext.3 json all
  duti -s com.sublimetext.3 xml all
  duti -s com.sublimetext.3 public.unix-executable all
  duti -s com.sublimetext.3 public.plain-text all
  duti -s com.sublimetext.3 public.source-code all
fi

fancy_echo "Configuring Zsh ..."

shell_path=/usr/local/bin/zsh

if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
  fancy_echo "Adding '$shell_path' to /etc/shells"
  sudo sh -c "echo $shell_path >> /etc/shells"
fi

REALSHELL=$(dscl . -read "/Users/$USER/" UserShell | awk '{ print $2 }')
if [ "$REALSHELL" != "$shell_path" ]; then
  fancy_echo "Changing your shell from $SHELL to $shell_path ..."
  sudo chsh -s "$shell_path" "$USER"
fi

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

fancy_echo "Done Configuring Zsh!"

fancy_echo "Configuring ASDF ..."

if [ ! -d "$HOME/.asdf" ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.6.0
fi

# shellcheck disable=SC2016
# append_to_file $HOME/.zshrc '. $HOME/.asdf/asdf.sh'

# shellcheck disable=SC1090
. "$HOME/.asdf/asdf.sh"

asdf plugin-add ruby || true
asdf plugin-add python || true
asdf plugin-add nodejs || true

export NODEJS_CHECK_SIGNATURES=no

latest_python2() {
	asdf list-all python | grep -v - | grep -e "^2." | tail -1
}

latest_python3() {
	asdf list-all python | grep -v - | grep -e "^3." | tail -1
}

latest_ruby() {
	asdf list-all ruby | grep -v - | tail -1
}

latest_nodejs() {
	asdf list-all nodejs | grep -v - | tail -1
}

CPPFLAGS="-I$(brew --prefix zlib)/include -I$(brew --prefix sqlite3)/include" asdf install python "$(latest_python2)" || true
CPPFLAGS="-I$(brew --prefix zlib)/include -I$(brew --prefix sqlite3)/include" asdf install python "$(latest_python3)" || true
asdf install ruby "$(latest_ruby)" || true
asdf install nodejs "$(latest_nodejs)" || true

asdf global python "$(latest_python3) $(latest_python2)"
asdf global ruby "$(latest_ruby)"
asdf global nodejs "$(latest_nodejs)"

fancy_echo "Done Configuring ASDF!"

fancy_echo "Configuring Postgres ..."

createuser --superuser --createdb --createrole --replication postgres || true
createuser --superuser --createdb --createrole --replication root || true

fancy_echo "Done Configuring Postgres!"

GITHUB_USER="$(git config --get github.user)"

if [ -n "$GITHUB_USER" ]; then

  LICENSES_URL="https://github.com/$GITHUB_USER/licenses"
  if git ls-remote "$LICENSES_URL" &>/dev/null; then
    echo "Fetching $GITHUB_USER/licenses from GitHub:"
    if [ ! -d "$HOME/.licenses" ]; then
      echo "Cloning to ~/.licenses:"
      git clone $Q "$LICENSES_URL" ~/.licenses
    else
      (
        cd ~/.licenses
        git pull $Q --rebase --autostash
      )
    fi
    (
      cd ~/.licenses
      for i in script/setup script/bootstrap; do
        if [ -f "$i" ] && [ -x "$i" ]; then
          echo "Running licenses $i:"
          "$i" 2>/dev/null
          break
        fi
      done
    )
    echo ""
  fi

  SECRETS_URL="https://github.com/$GITHUB_USER/secrets"
  if git ls-remote "$SECRETS_URL" &>/dev/null; then
    echo "Fetching $GITHUB_USER/secrets from GitHub:"
    if [ ! -d "$HOME/.secrets" ]; then
      echo "Cloning to ~/.secrets:"
      git clone $Q "$SECRETS_URL" ~/.secrets
    else
      (
        cd ~/.secrets
        git pull $Q --rebase --autostash
      )
    fi
    (
      cd ~/.secrets
      for i in script/setup script/bootstrap; do
        if [ -f "$i" ] && [ -x "$i" ]; then
          echo "Running secrets $i:"
          "$i" 2>/dev/null
          break
        fi
      done
    )
    echo ""
  fi

fi

fancy_echo "Configuring macOS settings..."

# macOS defaults

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Reveal IP address, hostname, OS version, etc. when clicking the clock
# in the login window
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Trackpad: map bottom right corner to right-click
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

# Enable full keyboard access for all controls
# (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Use scroll gesture with the Ctrl (^) modifier key to zoom
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144
# Follow the keyboard focus while zoomed in
defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1 # normal minimum is 2 (30 ms)
defaults write NSGlobalDomain InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)

# Save screenshots to the ~/Pictures/Screenshots folder
defaults write com.apple.screencapture location -string "${HOME}/Pictures/Screenshots"

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

# Set Desktop as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"

# Show icons for hard drives, servers, and removable media on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -bool true

# Enable highlight hover effect for the grid view of a stack (Dock)
defaults write com.apple.dock mouse-over-hilite-stack -bool true

# https://apple.stackexchange.com/questions/27544/how-to-completely-disable-auto-save-and-versions-in-mac-os-x-lion
defaults write -g ApplePersistence -bool no

fancy_echo "Done configuring macOS!"

echo "Done. Note that some of these changes require a logout/restart to take effect."
