#!/bin/sh
# Install all dotfiles into the home directory
# Adapted from https://github.com/MikeMcQuaid/dotfiles/blob/master/script/setup

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

for DOTFILE in *; do
  HOMEFILE="$HOME/.$DOTFILE"
  [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"
  DIRFILE="$DOTFILESDIR/$DOTFILE"

  echo $DOTFILE | egrep -q '(^script/$|\.txt$|\.md$)' && continue

  # Don't install some files unless you're also called Mike.
  if [echo $USER | grep -vq 'atul'] || [echo $USER | grep -vq 'johria']
  then
    echo $DOTFILE | grep -q 'gitconfig-user' && continue
    echo $DOTFILE | grep -q 'ssh' && continue
    echo $DOTFILE | grep -q 'brew-cleanup-installed' && continue
  fi

  echo $DOTFILE | grep -q '\.sh' \
    && HOMEFILE="$HOME/.$(echo $DOTFILE | sed -e 's/\.sh//')"

  if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]
  then
    ln -sfv "$DIRFILE" "$HOMEFILE"
  else
    rm -rv "$HOMEFILE"
    ln -sv "$DIRFILE" "$HOMEFILE"
  fi
done
