#!/bin/sh
# Install all dotfiles into the home directory
# Adapted from https://github.com/MikeMcQuaid/dotfiles/blob/master/script/setup

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

[ $(uname -s) = "Darwin" ] && export OSX=1 && export UNIX=1
[ $(uname -s) = "Linux" ] && export LINUX=1 && export UNIX=1
uname -s | grep -q "_NT-" && export WINDOWS=1

for DOTFILE in *; do
  HOMEFILE="$HOME/.$DOTFILE"
  [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"
  DIRFILE="$DOTFILESDIR/$DOTFILE"

  echo $DOTFILE | egrep -q '(^script/$|\.txt$|\.md$)' && continue

  # Don't install some files unless you're also called Mike.
  if echo $USER | grep -vq 'mike'
  then
    echo $DOTFILE | grep -q 'gitconfig-user' && continue
    echo $DOTFILE | grep -q 'ssh' && continue
  fi

  echo $DOTFILE | grep -q '\.sh' \
    && HOMEFILE="$HOME/.$(echo $DOTFILE | sed -e 's/\.sh//')"

  if [ $UNIX ]
  then
    if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]
    then
      ln -sfv "$DIRFILE" "$HOMEFILE"
    else
      rm -rv "$HOMEFILE"
      ln -sv "$DIRFILE" "$HOMEFILE"
    fi
  else
    cp -rv "$DIRFILE" "$HOMEFILE"
  fi
done

append_to_file() {
  local file="$1"
  local text="$2"
  
  if [ -e "$file" ];
  then
    if ! grep -qs "^$text$" "$file"; then
      printf "\n%s\n" "$text" >> "$file"
    fi
  else
    touch "$file"
    printf "%s\n" "$text" >> "$file"
  fi
}

if [ $OSX ]
then
  mkdir -p "$HOME/Library/Application Support/Sublime Text 3/Installed Packages/"
  if [ ! -f "$HOME/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package" ]; then
    # http://stackoverflow.com/questions/19529999/add-package-control-in-sublime-text-3-through-the-command-line
    echo "Installing Sublime Text 3 Package Manager"
    wget http://sublime.wbond.net/Package%20Control.sublime-package -P "$HOME/Library/Application Support/Sublime Text 3/Installed Packages/"
  fi

  duti -s com.sublimetext.3 java all
  duti -s com.sublimetext.3 js all
  duti -s com.sublimetext.3 py all
  duti -s com.sublimetext.3 rb all
  duti -s com.sublimetext.3 sh all
  duti -s com.sublimetext.3 json all
  duti -s com.sublimetext.3 xml all
  duti -s com.sublimetext.3 public.unix-executable all
  duti -s com.sublimetext.3 public.plain-text all
  duti -s com.sublimetext.3 public.source-code all
fi

brew bundle --global

eval "$(pyenv init -)"
pyenv install --skip-existing 2.7.13
pyenv install --skip-existing 3.6.0
pyenv global 3.6.0 2.7.13
pyenv rehash
pip3 install virtualenvwrapper
pip2 install virtualenvwrapper

# use homebrew python 2 packages in system python and pyenv python
mkdir -p ~/Library/Python/2.7/lib/python/site-packages
append_to_file "$HOME/Library/Python/2.7/lib/python/site-packages/homebrew.pth" "import sys; sys.path.insert(1, '$(brew --prefix)/lib/python2.7/site-packages')"
append_to_file "$(dirname $(pyenv which python2))/../lib/python2.7/site-packages/homebrew.pth" "import sys; sys.path.insert(1, '$(brew --prefix)/lib/python2.7/site-packages')"

# use homebrew python 3 packages in system python and pyenv python
mkdir -p ~/Library/Python/3.6/lib/python/site-packages
append_to_file "$HOME/Library/Python/3.6/lib/python/site-packages/homebrew.pth" "import sys; sys.path.insert(1, '$(brew --prefix)/lib/python3.6/site-packages')"
append_to_file "$(dirname $(pyenv which python3))/../lib/python3.6/site-packages/homebrew.pth" "import sys; sys.path.insert(1, '$(brew --prefix)/lib/python3.6/site-packages')"

eval "$(rbenv init -)"
rbenv install --skip-existing 2.2.2
rbenv install --skip-existing 2.4.0
rbenv global 2.2.2
rbenv rehash
gem update --system
gem install bundler
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))
rbenv rehash

eval "$(nodenv init -)"
nodenv install --skip-existing 7.7.2
nodenv global 7.7.2

GITHUB_USER="$(git config --get github.user)"

LICENSES_URL="https://github.com/$GITHUB_USER/licenses"
if [ ! -d "$HOME/.licenses" ]; then
  log "Cloning to ~/.licenses:"
  git clone $Q "$LICENSES_URL" ~/.licenses
else
  (
    cd ~/.licenses
    git pull $Q --rebase --autostash
  )
fi
